// import './global.css'
import "bootstrap/dist/css/bootstrap.min.css"
import 'remixicon/fonts/remixicon.css'
import '../app/css/nav.css'
import '../app/css/page1.css'
import '../app/css/footer.css'
import '../app/css/profile.css'
import './global.css'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: 'Internshala',
  description: 'Generated by create next app',
  
}
import Wrapper from '@/Components/wrapper/Wrapper'
import NextTopLoader from "nextjs-toploader"

export default function RootLayout({ children }) {
  <link
  rel="icon"
  href="https://play-lh.googleusercontent.com/8t6U6HGuMnP1DAJYpb4U_fEwVA7fgaOBJYRyfPHM5OLZllGj-8tsmJhu6Y4ikMrGpZg"
  type="image/<generated>"
  sizes="<generated>"
/>
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Wrapper>
        <NextTopLoader />
          {children}
        </Wrapper>
      </body>
    </html>
  )
}
